### PR TITLE
Adding CGI .htaccess

### PR DESCRIPTION
**Pull request by kentaromiura**
I added a special .htaccess which let polpetta using any real CGI script as long as the script is an executable file, I added a optionalDependency on cgi (also it's pointing to mine copy since npm version is quite old and doesn't handle cwd), I tried on my raspberry pi and it's pretty fast.

### CODE REVIEW

**Comment by kentaromiura** [comment]
actually wait until I fix the problem with no executable files not being processed anymore :P

**Comment by WebReflection** [comment]
there is some sort of CGI support already, quite experimental, but it was there … right?

**Comment by kentaromiura** [comment]
is there? the only thing similar to it is the njs part, but I couldn't see no real cgi (unless is undocumented stuff)

**Comment by WebReflection** [comment]
sorry, I had coffee now … and I meant there is an experimental `.htaccess` logic in place already … https://github.com/WebReflection/polpetta/tree/master/src/htaccess

**Comment by kentaromiura** [comment]
yes, I _am_ using htaccess to provide cgi compatibility, it works pretty well now that I fixed the stat issue. you can pull now and see it yourself running polpetta in the example cgi-bin directory, you can run any kind of executable as long as they act as a cgi. I can add later some python, ruby, go, examples, you can also run js if you want.

**Pull request merged**
